Models/Contacto.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace tallerPuntoNet.Models
{
    public class Contacto
    {
        [Required]
        [MaxLength(100)]
       public string nombre {get ; set;}

       [Required]
        [MaxLength(100)]
       public string apellido {get ; set;}

       [Required]
        [DataType(DataType.PhoneNumber)]
       public string telefono {get ; set;}

       [Required]
        [EmailAddress]
       public string email {get ; set;}

        [Required]
        [MaxLength(500)]
       public string mensaje {get;set;}


    }
}

Models/ErrorViewModel.cs
using System;

namespace tallerPuntoNet.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Controllers/ContactoAPIController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using tallerPuntoNet.Models;

namespace tallerPuntoNet.Controllers
{
    public class ContactoAPIController : Controller
    {

        [HttpPost]
       
        
        public Contacto Index([FromBody]Contacto fc)
        {
            return fc;
        }


    }
}

Controllers/FormularioContactoController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using tallerPuntoNet.Models;

namespace tallerPuntoNet.Controllers
{
    public class FormularioContactoController : Controller
    {
        private readonly ILogger<FormularioContactoController> _logger;

        public FormularioContactoController(ILogger<FormularioContactoController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Index(Contacto fc)
        {
            if(ModelState.IsValid){
                return Redirect("/Home/Privacy");
            }
            return View(fc);
        }


        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        [HttpPost]
        [Route("/contacto")]
        
        public Contacto crearContacto(Contacto fc)
        {
            return fc;
        }


    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using tallerPuntoNet.Models;

namespace tallerPuntoNet.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/FormularioContacto/Index.cshtml
@model Contacto
@{
    ViewData["Title"] = "Contacto";
}

<div class="container">
  <div class="row">
    <div class="column">
      
    </div>
    <div class="column">
      <form asp-controller="FormularioContacto" asp-action="Index" method="post">
        
        <input type="text" id="fname" name="nombre" placeholder="Nombre" asp-for="nombre">
        <span asp-validation-for="nombre" class="text-danger"></span>
        <br>
        <input type="text" id="lname1" name="apellido" placeholder="Apellido" asp-for="apellido">
        <span asp-validation-for="apellido" class="text-danger"></span>
        <br>
         <input type="text" id="lname2" name="telefono" placeholder="Telefono" asp-for="telefono">
        <span asp-validation-for="telefono" class="text-danger"></span>
        <br>
        <input type="text" id="lname3" name="email" placeholder="Correo electronico" asp-for="email">
        <span asp-validation-for="email" class="text-danger"></span>
        <br>
        <textarea id="subject" name="mensaje" placeholder="Mensaje" style="height:170px" asp-for="mensaje"></textarea>
        <span asp-validation-for="mensaje" class="text-danger"></span>
        <br>
        <input type="submit" value="Submit">
      </form>
    </div>
  </div>
</div>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - tallerPuntoNet</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">tallerPuntoNet</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="FormularioContacto" asp-action="Index">Contacto</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - tallerPuntoNet - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>